import { IComment } from '@/interface/forum.interface';

export const mockComments: IComment[] = [
  {
    id: '1',
    createdAt: '2021-01-01',
    message: 'This is a comment',
    createdBy: 'John Doe',
    likes: 10,
    downvotes: 2,
    replies: [
      {
        id: '10',
        createdAt: '2021-01-01',
        message: 'This is a reply',
        createdBy: 'John Doe',
        likes: 10,
        downvotes: 2,
        replies: [
          {
            id: '17',
            createdAt: '2021-01-01',
            message: 'This is a reply',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [],
          },
        ],
      },
      {
        id: '20',
        createdAt: '2021-01-01',
        message: 'This is a reply',
        createdBy: 'John Doe',
        likes: 10,
        downvotes: 2,
        replies: [],
      },
    ],
  },
  {
    id: '2',
    createdAt: '2021-01-01',
    message: 'This is a comment',
    createdBy: 'John Doe',
    likes: 10,
    downvotes: 2,
    replies: [
      {
        id: '21',
        createdAt: '2021-01-01',
        message: 'This is a reply',
        createdBy: 'John Doe',
        likes: 10,
        downvotes: 2,
        replies: [
          {
            id: '1',
            createdAt: '2021-01-01',
            message: 'This is a comment',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [
              {
                id: '10',
                createdAt: '2021-01-01',
                message: 'This is a reply',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [
                  {
                    id: '17',
                    createdAt: '2021-01-01',
                    message: 'This is a reply',
                    createdBy: 'John Doe',
                    likes: 10,
                    downvotes: 2,
                    replies: [],
                  },
                ],
              },
              {
                id: '20',
                createdAt: '2021-01-01',
                message: 'This is a reply',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [],
              },
            ],
          },
          {
            id: '2',
            createdAt: '2021-01-01',
            message: 'This is a comment',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [
              {
                id: '21',
                createdAt: '2021-01-01',
                message: 'This is a reply',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [],
              },
            ],
          },
          {
            id: '3',
            createdAt: '2021-01-01',
            message: 'This is a comment',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: '3',
    createdAt: '2021-01-01',
    message: 'This is a comment',
    createdBy: 'John Doe',
    likes: 10,
    downvotes: 2,
    replies: [
      {
        id: '1',
        createdAt: '2021-01-01',
        message: 'This is a comment',
        createdBy: 'John Doe',
        likes: 10,
        downvotes: 2,
        replies: [
          {
            id: '10',
            createdAt: '2021-01-01',
            message: 'This is a reply',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [
              {
                id: '17',
                createdAt: '2021-01-01',
                message: 'This is a reply',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [],
              },
            ],
          },
          {
            id: '20',
            createdAt: '2021-01-01',
            message: 'This is a reply',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [],
          },
        ],
      },
      {
        id: '2',
        createdAt: '2021-01-01',
        message: 'This is a comment',
        createdBy: 'John Doe',
        likes: 10,
        downvotes: 2,
        replies: [
          {
            id: '21',
            createdAt: '2021-01-01',
            message: 'This is a reply',
            createdBy: 'John Doe',
            likes: 10,
            downvotes: 2,
            replies: [
              {
                id: '1',
                createdAt: '2021-01-01',
                message: 'This is a comment',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [
                  {
                    id: '10',
                    createdAt: '2021-01-01',
                    message: 'This is a reply',
                    createdBy: 'John Doe',
                    likes: 10,
                    downvotes: 2,
                    replies: [
                      {
                        id: '17',
                        createdAt: '2021-01-01',
                        message: 'This is a reply',
                        createdBy: 'John Doe',
                        likes: 10,
                        downvotes: 2,
                        replies: [],
                      },
                    ],
                  },
                  {
                    id: '20',
                    createdAt: '2021-01-01',
                    message: 'This is a reply',
                    createdBy: 'John Doe',
                    likes: 10,
                    downvotes: 2,
                    replies: [],
                  },
                ],
              },
              {
                id: '2',
                createdAt: '2021-01-01',
                message: 'This is a comment',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [
                  {
                    id: '21',
                    createdAt: '2021-01-01',
                    message: 'This is a reply',
                    createdBy: 'John Doe',
                    likes: 10,
                    downvotes: 2,
                    replies: [
                      {
                        id: '1',
                        createdAt: '2021-01-01',
                        message: 'This is a comment',
                        createdBy: 'John Doe',
                        likes: 10,
                        downvotes: 2,
                        replies: [
                          {
                            id: '10',
                            createdAt: '2021-01-01',
                            message: 'This is a reply',
                            createdBy: 'John Doe',
                            likes: 10,
                            downvotes: 2,
                            replies: [
                              {
                                id: '17',
                                createdAt: '2021-01-01',
                                message: 'This is a reply',
                                createdBy: 'John Doe',
                                likes: 10,
                                downvotes: 2,
                                replies: [],
                              },
                            ],
                          },
                          {
                            id: '20',
                            createdAt: '2021-01-01',
                            message: 'This is a reply',
                            createdBy: 'John Doe',
                            likes: 10,
                            downvotes: 2,
                            replies: [],
                          },
                        ],
                      },
                      {
                        id: '2',
                        createdAt: '2021-01-01',
                        message: 'This is a comment',
                        createdBy: 'John Doe',
                        likes: 10,
                        downvotes: 2,
                        replies: [
                          {
                            id: '21',
                            createdAt: '2021-01-01',
                            message: 'This is a reply',
                            createdBy: 'John Doe',
                            likes: 10,
                            downvotes: 2,
                            replies: [],
                          },
                        ],
                      },
                      {
                        id: '3',
                        createdAt: '2021-01-01',
                        message: 'This is a comment',
                        createdBy: 'John Doe',
                        likes: 10,
                        downvotes: 2,
                        replies: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: '3',
                createdAt: '2021-01-01',
                message: 'This is a comment',
                createdBy: 'John Doe',
                likes: 10,
                downvotes: 2,
                replies: [],
              },
            ],
          },
        ],
      },
      {
        id: '3',
        createdAt: '2021-01-01',
        message: 'This is a comment',
        createdBy: 'John Doe',
        likes: 10,
        downvotes: 2,
        replies: [],
      },
    ],
  },
];
